# Generated by Django 3.2.6 on 2022-11-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvrage',
            name='discipline',
        ),
    ]
