# Generated by Django 3.2.6 on 2022-11-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_remove_ouvrage_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametre.discipline', verbose_name='discipline'),
            preserve_default=False,
        ),
    ]
