# Generated by Django 3.2.6 on 2023-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0004_remove_partenaire_siteweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='siteweb',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='site web'),
        ),
    ]
