# Generated by Django 3.2.6 on 2023-03-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0005_partenaire_siteweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='laboratoire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ufr',
        ),
    ]
