# Generated by Django 3.2.6 on 2023-03-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0006_auto_20230310_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='discipline',
        ),
        migrations.AddField(
            model_name='article',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.laboratoire', verbose_name='laboratoire'),
        ),
        migrations.AddField(
            model_name='article',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.specialite', verbose_name='spécialité'),
        ),
        migrations.AddField(
            model_name='article',
            name='ufr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.ufr', verbose_name='ufr'),
        ),
    ]
