# Generated by Django 3.2.6 on 2023-03-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0007_auto_20230310_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametre.discipline', verbose_name='discipline'),
            preserve_default=False,
        ),
    ]
