# Generated by Django 3.2.6 on 2023-03-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0008_article_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.discipline', verbose_name='discipline'),
        ),
    ]
