# Generated by Django 3.2.6 on 2022-10-03 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenoms', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='prénoms')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='e-mail')),
                ('periode_abonnement', models.CharField(choices=[('Annuelle', 'Annuelle'), ('Semestrielle', 'Semestrielle'), ('Trimestrielle', 'Trimestrielle'), ('Mensuelle', 'Mensuelle')], default='Annuelle', max_length=15, verbose_name="période d'abonnement")),
                ('date_debut', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date de fin')),
                ('type_abonne', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant'), ('Autres', 'Autres')], default='Etudiant', max_length=15, verbose_name="type d'abonné")),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='genre')),
                ('matricule', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='matricule')),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.civilite', verbose_name='civilité')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
