# Generated by Django 3.2.6 on 2022-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonne',
            name='montant',
            field=models.IntegerField(blank=True, default=0, verbose_name='montant'),
        ),
        migrations.AddField(
            model_name='abonne',
            name='regle',
            field=models.BooleanField(blank=True, default=True, verbose_name='reglé'),
        ),
    ]
