# Generated by Django 3.2.6 on 2022-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0003_alter_abonne_regle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonne',
            options={'ordering': ('nom', 'prenoms')},
        ),
        migrations.AlterField(
            model_name='abonne',
            name='prenoms',
            field=models.CharField(default=1, max_length=100, verbose_name='prénoms'),
            preserve_default=False,
        ),
    ]
