# Generated by Django 3.2.6 on 2022-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0004_auto_20221030_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonne',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='numéro'),
        ),
    ]
