# Generated by Django 3.2.6 on 2023-03-10 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0005_abonne_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='date_debut',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date début'),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='date_fin',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date fin'),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='periode_abonnement',
            field=models.CharField(choices=[('Annuelle', 'Annuelle'), ('Semestrielle', 'Semestrielle'), ('Trimestrielle', 'Trimestrielle'), ('Mensuelle', 'Mensuelle')], default='Annuelle', max_length=15, verbose_name='périodicité'),
        ),
    ]
