# Generated by Django 3.2.6 on 2023-03-13 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0006_auto_20230310_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonne', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant'), ('Autres', 'Autres')], default='Etudiant', max_length=15, verbose_name="type d'abonné")),
                ('periode_abonnement', models.CharField(choices=[('Annuelle', 'Annuelle'), ('Semestrielle', 'Semestrielle'), ('Trimestrielle', 'Trimestrielle'), ('Mensuelle', 'Mensuelle')], default='Annuelle', max_length=15, verbose_name='périodicité')),
                ('date_debut', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date début')),
                ('date_fin', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date fin')),
                ('date_saisie', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date début')),
                ('montant', models.IntegerField(blank=True, default=0, verbose_name='montant')),
                ('regle', models.BooleanField(blank=True, default=False, verbose_name='reglé')),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonne.abonne', verbose_name='abonne')),
            ],
            options={
                'ordering': ('date_saisie',),
            },
        ),
    ]
