# Generated by Django 3.2.6 on 2023-03-13 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0007_abonnement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonne',
            options={'ordering': ('type_abonne',)},
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='cellulaire',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='email',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='periode_abonnement',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='prenoms',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='regle',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_saisie',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date saisie'),
        ),
    ]
