# Generated by Django 3.2.6 on 2023-03-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0009_alter_article_discipline'),
        ('abonne', '0008_auto_20230313_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonne',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametre.profil', verbose_name='profil'),
            preserve_default=False,
        ),
    ]
