# Generated by Django 3.2.6 on 2023-03-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0009_abonne_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonne',
            name='civilite',
        ),
    ]
