# Generated by Django 3.2.6 on 2023-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0010_remove_abonne_civilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='matricule'),
        ),
    ]
