# Generated by Django 3.2.6 on 2023-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonne', '0011_alter_abonne_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonne',
            name='profil',
        ),
        migrations.AddField(
            model_name='abonne',
            name='cellulaire',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='cellulaire'),
        ),
    ]
