# Generated by Django 3.2.6 on 2023-03-07 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(blank=True, choices=[('Actualité', 'Actualité'), ('Réunion', 'Réunion'), ('Rencontre', 'Rencontre')], max_length=255, verbose_name="type d'évènement")),
                ('titre', models.CharField(blank=True, max_length=255, verbose_name="titre de l'évènement")),
                ('date_du', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='du')),
                ('date_au', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='au')),
                ('date_publication', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date publication')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('resume', models.TextField(blank=True, default='', null=True, verbose_name='résumé')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/evenements', verbose_name='photo evènement')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/evenements', verbose_name='photo')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='fichier/evenements', verbose_name='vidéo / autres fichiers')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actualite.evenement', verbose_name='evènement')),
            ],
        ),
    ]
